### ISSUE TITLE
Problem in SingleEvioEventFileSource.cc

### ISSUE THREAD

**Issue by cissieAB** [JeffersonLab/JANA4ML4FPGA#32]
https://github.com/JeffersonLab/JANA4ML4FPGA/blob/ee1fa8fe74523375170d21f4ecf0a35ed8862ec3/src/plugins/single_event_evio/SingleEvioEventFileSource.cc#L49-L52

@DraTeots 

In the above lines, you bind buff to block.data, and block.data is set to be of length m_buff_len. But the useful data length is cur_len. The followed (m_buff_len-cur_len) data will be filled with 0. Then you pass this block with extra 0s to parser, the parser detect those 0s and complain "Unknown outer EVIO bank tag: 0". 

If you really want to use this plugin, I think you should fix this and mark #31 as solved.

**Comment by DraTeots** [comment]
Oh! Good! Thanks! No I think I will make a PR removing SingleEvioEventFileSource in favor of CDAQfile.
