### ISSUE TITLE
Save EVIO from TCP stream

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/JANA4ML4FPGA#46]
Currently EVIO reader can save EVIO files, but this happens internally, without introducing EVIO blocks as JANA factories. So if EVIO is received by TCP or other sources it is not straightforward to save EVIO. 

This ticket is simple - we need to save received EVIO to file. But it would be beneficial to make it the proper way probably through introducing EVIO blocks factory (or whatever), EVIOWriteProcessor and what is needed.

**Comment by faustus123** [comment]
This was resolved with PR #51 and PR #53
